name: Run Smart Contract Tests

on: [push]
    
jobs:
  my_job:
    name: Private Network Docker Smart Contract Test
    runs-on: ubuntu-18.04
    steps:
    - uses: isbang/compose-action@v0.2.0
    - uses: actions/checkout@v1
    - name: install cleos
      run: |
        wget https://github.com/eosio/eos/releases/download/v2.0.9/eosio_2.0.9-1-ubuntu-18.04_amd64.deb
        sudo apt install ./eosio_2.0.9-1-ubuntu-18.04_amd64.deb          
    - name: run test shell script
      run: pwd && ls && ./ignition.sh
