name: Run Smart Contract Tests

on: [push]
    
jobs:
  my_job:
    name: Private Network Docker Smart Contract Test
    runs-on: ubuntu-latest
    steps:
    - uses: isbang/compose-action@v0.2.0
    - uses: actions/checkout@v1
    - name: run test shell script
      run: pwd && ls && ./ignition.sh
